frontend:
  image: vindsburg/assessment-front
  replicas: 2
  resources:
    requests:
      cpu: "800m"
      memory: "128Mi"
    limits:
      memory: "256Mi"
  ingress:
    host: frontend.example.com
    adminWhitelist: "192.168.0.0/24"
    apiInternalWhitelist: "10.0.0.0/16"
    paths:
    - path: /
      service: frontend
      port: 8080
    - path: /admin
      service: frontend
      port: 8080
    - path: /api/internal
      service: frontend
      port: 8080

frontendAutoscaling:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80  

backend:
  image: vindsburg/assessment-back
  replicas: 2
  resources:
    requests:
      cpu: "800m"
      memory: "128Mi"
    limits:
      memory: "256Mi"

backendAutoscaling:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

database:
  image: postgres:15
  user: app_user  # TODO: use a secrets manager tool
  password: app_password  # TODO: use a secrets manager tool
  name: app_db
  replicas: 2
  storage:
    size: 5Gi

ingress-nginx:
  controller:
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
    service:
      enabled: true
    metrics:
      enabled: true
    admissionWebhooks:
      enabled: true
