apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  replicas: {{ .Values.database.replicas }}
  selector:
    matchLabels:
      app: database
  serviceName: "database"
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: {{ .Values.database.image }}
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "database.secretName" . }}
              key: database-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "database.secretName" . }}
              key: database-password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ template "database.secretName" . }}
              key: database-name
        volumeMounts:
        - name: database-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: database-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.database.storage.size }}