apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-admin
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.frontend.ingress.adminWhitelist }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.frontend.ingress.host }}
    http:
      paths:
      - path: /admin
        pathType: Exact
        backend:
          service:
            name: frontend
            port:
              number: 8080