apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  database-user: {{ .Values.database.user | b64enc }}
  database-password: {{ .Values.database.password | b64enc }}
  database-url: {{ printf "postgresql://%s:%s@database:5432/%s" .Values.database.user .Values.database.password .Values.database.name | b64enc }}
